### ISSUE TITLE
Not able to assign actions to buttons while in the Home App. 

### ISSUE THREAD

**Issue by retroaces** [thenewwazoo/homebridge-lutron-caseta-leap#161]
**Describe The Bug:**

While in the Apple Home App and attempting to assign actions (i.e. turn on lamp to 100%), I get the error message "Could not complete operation". 

I don't get any errors or log outputs indicating something weird happening, just does not let me assign an action to a button.

I have been running this plugin for well over a year without issues, but all the sudden, I cannot assign actions to buttons.

I can see activity in the logs that I am pressing the buttons of the pico remote, and it receives information. They are getting feedback. However, I am not able to assign anything to the buttons.
**To Reproduce:**

I am running Homebridge on my Mac Mini Catalina and I have the Lutron Caseta Leap plugin running on the latest version as a child bridge. 
**Expected behavior:**

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**
![IMG_7439](https://github.com/user-attachments/assets/a647be35-c2a4-4ffd-b216-fcce2531c707)

**Environment:**

* **Plugin Version**: V2.60
* **Homebridge Version**: 
* **Node.js Version**: 20.10.0
* **NPM Version**: 
* **Operating System**:

**Comment by sebastiangoldstein** [comment]
I am having the same issue. 
As for items already assigned to my Picos I have no issues however I cannot assign new actions without getting the "Could not complete operations" pop up. I have been using this plug-in for well over a year without issue.

**Comment by RyanJanak** [comment]
I am experiencing this issue as well. Buttons indicate they are being pressed in Home app, but I'm unable to assign actions.

**Comment by sebastiangoldstein** [comment]
**Fix discovered for this issue!**
**"Could Not Complete Operation" HomeKit Error Message**

@RyanJanak  & @thenewwazoo,
I don't believe this issue has anything to do with the Leap plugin (Though it may). Here is how I finally resolved the issue:

I spent 2 weeks back and forth with Apple support. They could not help. I sent in screen recording logs, restarted home hubs, etc., but short of telling me to blow up my entire HomeKit Setup and start over, they had no solutions.

Finally, I purchased the App: "Controller for Homekit." (I have since learned you can do this would out purchasing an app by downloading the free app: "Eve." In both of these apps (Controller and Eve), the stock Apple Home app cannot is show me old, broken, and deleted Automations, Scenes, and Smart button assignments. 

Using the Controller for HomeKit App, I was able to **locate and see all of my home hub’s saved automations, scenes, and button assignments - including ones that I had "deleted" but were “stuck” in limbo.** Most, if not all of these were previous Leap button assignments. 

These “stuck” automation and smart button assignments prevented me from creating new automation with the same or similar functions.  

I systematically found and deleted each one of these “old Stuck Automation" (Note: None of these were visible in the Apple Home App. I had well over 30 to delete).  Once this process was complete. I reset MacOS's HomeKit cache by 1) Turning off the HomeKit syncing in iCloud and 2) Restarting every Home hub. 3) restarting every Apple device. 

Immediately I was once again able to create automation and assign smart button and LEAP functionality..
I hope this information helps you resolve this as well.
-Sebastian

**Comment by retroaces** [comment]
@sebastiangoldstein 

Thank you so much Sebastian! This fixed my issue completely so far. I’ve got the eve app on my phone but never would have thought about going through all my old rules, automations that aren’t valid anymore. I really appreciate you taking the time to describe how you troubleshooted and ultimately fixed this!!

@RyanJanak @thenewwazoo 

see above for fix.

**Comment by RyanJanak** [comment]
That's it! Deleting the ghost automations, then rebooting all my Home hubs solved it! Thanks @sebastiangoldstein

**Comment by thenewwazoo** [comment]
If someone who benefitted from this wanted to add a writeup to the troubleshooting section of the README, I'd gratefully accept the PR! :) For now, since this is resolved, I'm going to close the issue.
