### ISSUE TITLE
Enable toggle to hide Pico remotes already paired to switches in Caseta app

### ISSUE THREAD

**Issue by enz1ey** [thenewwazoo/homebridge-lutron-caseta-leap#17]
It would be very helpful (and help keep the Home app clean) if there was a toggle to hide Pico remotes which are already paired with a Lutron Caseta switch in the Caseta app, and thus cannot be used separately in HomeKit.

**Comment by thenewwazoo** [comment]
To anyone who wants to pick this up, the hard work [has been done](https://github.com/thenewwazoo/homebridge-lutron-caseta-leap/blob/master/src/PicoRemote.ts#L115), it just needs to be updated for multi-BG cases and made configurable.

**Comment by rocketis** [comment]
this would be great, I have 19 picos already controlling Caseta lights and Fans, I want to hide those, they just clutter the homekit interface.

**Comment by thenewwazoo** [comment]
I agree! The big question right now is how to make it configurable without breaking user configs. Now that I’ve got the config GUI built, it may be easier. Unfortunately, I’m unlikely to have time to work on this soon.

**Comment by michaelacosta-rpi** [comment]
I would agree this is almost a must-have. Ideally I would be able to select which remotes I want exposed to homekit. Otherwise, I have 10 remotes whose functionality I don't want to change in the home app. I understand some people might want to add additional functionality to the already paired switches (setting scenes when lights are turned on) but really you can already make automations for that. I want this plugin because the switch _doesn't_ control anything else.

**Comment by thenewwazoo** [comment]
I just released v2.4.0-beta0, which adds support for a global toggle to disable Picos that are already paired in the Lutron app. Give it a try and let me know how it works for you.

Please note that changing the in-Lutron-app associations will not have any effect on HomeKit until Homebridge is restarted.

**Comment by thenewwazoo** [comment]
Shipped in 2.4.0!
