### ISSUE TITLE
Discover serial number

### ISSUE THREAD

**Issue by JJTech0130** [thenewwazoo/homebridge-lutron-caseta-leap#24]
**Is your feature request related to a problem? Please describe:**

It seems like it would be really annoying to have to manually find the bridge's serial number, then run a script, just to get the certs.
**Describe the solution you'd like:**

On my HWQS system, it exposes a MDNS TXT record SERNUM, and I was wondering if it would be possible to use this to generate the certificates? I don't have a Caseta system, so I can't test that part.
**Describe alternatives you've considered:**

Would be OK if it just made you enter the serial number, but ran the script itself, not manually.
**Additional context:**

**Comment by thenewwazoo** [comment]
In the Caseta case, you have to initiate a certificate signing request, and then press a button on the back of the hub that is right next to the serial number. It's always bugged me that you have to know the IP address of the device (which may be harder for some users to figure out). Even if I used mDNS to discover the new hub, it may be necessary to require either the serial number or the IP address for disambiguation, but that is probably a pretty rare case.

I suspect the cert generation script could:
* If no serial number supplied, do an mDNS lookup for hubs
* If multiple hubs discovered w/o provided s/n, fail
* Connect in physical access mode, prompt user to press button
* Generate certificates
* Emit s/n alongside certificates

Right now I use a regex to extract the s/n from the hostname, and a TXT record is a much, much better solution.

I don't think this would be super hard to write.

**Comment by JJTech0130** [comment]
And perhaps if you could detect whether the link button is pressed and there are multiple hubs, pick the one with the link button pressed

**Comment by thenewwazoo** [comment]
@JJTech0130 I'm working on this UI right now. Any interest in being a tester? 😃

**Comment by JJTech0130** [comment]
While I'm more than willing to help, I don't actually have a Caseta system, so I don't think I'd be the best tester 😂

**Comment by thenewwazoo** [comment]
I just dropped a beta that adds bridge discovery. What happens when you try to use it?  😂

**Comment by thenewwazoo** [comment]
Okay, so thanks to some awesome users testing this for me, the bridge discovery code is looking pretty good. The Homebridge settings UI will now populate any bridges it finds (that answer to `_lutron._tcp` PTR lookups). It then asks for a SRV record to extract the serial number. Caseta bridges don't have the TXT record you mention:
```
Lutron\032Status._lutron._tcp.local. 10	IN SRV	0 0 22 Lutron-032e7e88.local.
Lutron\032Status._lutron._tcp.local. 10	IN TXT	"MACADDR=90:70:65:e3:8f:25" "CODEVER=08.07.12f000" "DEVCLASS=08040100" "FW_STATUS=1:NoUpdate" "NW_STATUS=InternetWorking" "ST_STATUS=good" "SYSTYPE=SmartBridge"
Lutron-032e7e88.local.	10	IN	A	192.168.1.151
Lutron-032e7e88.local.	10	IN	AAAA	fe80::9270:65ff:fee3:8f25
```
I'm curious to know if other device types have similar records.

In any case, the bridge finder now returns the systype along with IP and serial number information. The user of the BridgeFinder is responsible for managing secrets and constructing the SmartBridge object. Presumably it would be the same for some other bridge type.

I'm going to go ahead and close this up, since I think it fulfills the request (no need for users to discover their serial numbers and run a script to get the cert).
