### ISSUE TITLE
Timing of Light Actrion

### ISSUE THREAD

**Issue by mmfromut** [thenewwazoo/homebridge-lutron-caseta-leap#34]
**Describe Your Problem:**

I'm testing the plugin using Homebridge from my iMac and an Ipad as the Home Hub.  When I click the configured button, it takes about 2 seconds for the light to come on.  It's a noticable delay - is that normal?  I'm testing before dropping around $5k on Caseta switches and Picos identified to run a new house.  

Also, is there a way to make a button toggle the scene on/off.  For example, i want button one to turn on entertain which is linked to 3 switches.  It should turn them all on.  if pushed again, the behavior would be to turn them off.  I'm essentially trying to use PICOS instead of RadioRa2 multibutton keypads

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by thenewwazoo** [comment]
To the first question, no, I'm not aware of a way to speed it up. There are a few layers of indirection (remote -> hub -> homebridge -> homekit) that add up. I haven't really done any performance tuning of the plugin, so if you have any ideas, I'd love to hear them. NodeJS code is not my forte, for sure.

To the second question, no, Homekit scenes are idempotent. Once you set it, it's just set. There's no un-setting it because there's no concept of what was "before".
