### ISSUE TITLE
Support for Hoobs Please

### ISSUE THREAD

**Issue by BarnesGH** [thenewwazoo/homebridge-lutron-caseta-leap#50]
Would you be willing to accept a small payment to get this working with Hoobs or is that not possible? For some reason it says it’s Hoobs certified but I’ve seen where you said Hoobs isn’t supported. May I ask why? If you would accept payment just let me know. 
thank you for your work either way

**Comment by thenewwazoo** [comment]
Hi @BarnesGH! I apologize for giving the impression HOOBS is in any way certified. A user once reported to me that it worked for them, so I think the README used to say it worked (but doesn't now, it appears). If someone _else_ makes that claim, I'd like to correct them. :)

The biggest hinderance to supporting HOOBS is simply that I don't use it at home, and I don't have any kind of a "lab" setup for development. If the plugin running in dev breaks the hub, my real blinds stop working. 😅 I also have little free time, so the time I _do_ spend is usually trying to chase that damned client connection bug. All of that is to say that my ability to commit to working on the plugin in exchange for user support (monetary or otherwise) is limited. I don't want to establish any expectation I'm not certain I can deliver upon. Device-specific support like Pico remotes and occupancy sensors are one thing, but ecosystems like HOOBS are another.

I'm not sure what HOOBS' business model is, but they have [done work to support this plugin](https://github.com/hoobs-org/HOOBS/issues/1805) in the past, so it might be worth asking if they can commit resources.

If that doesn't work out and you really super duper want HOOBS support, I think at a minimum I'd need another hub to test with, at least one device, and something to run HOOBS on (if that's possible? does it require special hardware?). That's a lot to ask with no guarantees, though.

**Comment by BarnesGH** [comment]
I understand and appreciate what you have had time to do. I have a raspberry pi 4 with Hoobs but I might just add homebridge on there as well just for this. I have 4 pico switches that I’d love to get into HomeKit. If you do happen to have time to look at this let me know in advance and I’ll try to provide needed resources. 
Thanks for the quick reply!

**Comment by JBryant915** [comment]
I have it working in HOOBS myself. It was a while back that I installed it so I vaguely remember the process. When I first learned of the plugin and tried to install it, I had issues. I submitted issue reports with HOOBS and here on the Lutron Caseta github.  After about a day I got a response from HOOBS saying that it had been fixed and that I needed to remove the plugin, clear the entire HOOBS cache and then install the plugin and give it a try. I followed that and it worked. Thats from what I remember of it. It has worked great since. I have several of the Lutron Caseta switches that came with pico remotes that I didn't use and they were just taking up space in a drawer until this plugin came along. Of course there are things I wish they could do like double press or long press actions but hey, tey are very useful the way they are so I won't complain one little bit!! Thanks for taking the time to make this plugin @thenewwazoo this is one of the most useful plugins in my smart home setup.

**Comment by BarnesGH** [comment]
Well right on dude! I'll give it a go when I get home from work. I'll
remove the plugin, clear the cache, and re-install

**Comment by thenewwazoo** [comment]
I believe @JBryant915 ’s success might have been before I re-designed the configuration UI, which I think has implications for HOOBS. Do let me know how it goes.

**Comment by JBryant915** [comment]
I don’t know if it makes a difference, but I do keep up with the latest update and it still works. May not mean a thing though

**Comment by BarnesGH** [comment]
Implications in what regard?

**Comment by BarnesGH** [comment]
I just tried and got the same message, “please wait for the bridge to start.” 

I am on Hoobs version 4.0.7. I’ve put off updating because I’ve read some stories of people having issues, but I will give that a go.

**Comment by BarnesGH** [comment]
Well, the update wasn’t so smooth but I’m about done restoring my backup now. In the process it gave a command line that said, “ warning hoobg-lutron-caseta › ***@***.***: Broken version,do not use”

**Comment by BarnesGH** [comment]
I apologize for all the messages. I realize that my Hoobs wasn’t on the newest version even after reflashing from a newly downloaded image. I ran the update and tried the leap plugin again and alas, it worked! 

Thank you guys for the amount of time and work you’ve put in getting this sorted out, it is much appreciated.

**Comment by JBryant915** [comment]
Glad you got it sorted and that it’s working!! Like I said, this is one of the most useful plugins I use and I love it!!

**Comment by thenewwazoo** [comment]
Awesome! I'm super glad to hear it. I'm still a biiiit reluctant to put a HOOBS compatibility claim in the README, but if anyone from the future reads this and can confirm it works without additional effort required, drop me a line. For now, I'm going to close this issue up. Thanks again, @BarnesGH and @JBryant915!
