### ISSUE TITLE
Perpetual spinning gear when I open settings

### ISSUE THREAD

**Issue by robbrechter** [thenewwazoo/homebridge-lutron-caseta-leap#57]
**Describe Your Problem:**

I installed the plug-in and when I click settings, the loading gear icon just spins and spins. I've uninstalled/reinstalled and also rebooted Homebridge to no avail. I'm sure this is a very obvious oversight on my part.

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```
[7/26/2022, 11:52:18 PM] [Homebridge UI] [homebridge-lutron-caseta-leap] Incoming Request: /search
[7/26/2022, 11:52:22 PM] [Homebridge UI] [homebridge-lutron-caseta-leap] Terminating child process...
[7/26/2022, 11:52:22 PM] [Homebridge UI] [homebridge-lutron-caseta-leap] Child process ended

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**: latest stable and beta both behave the same
* **Homebridge Version**:  1.5.0
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:  Ubuntu Server

**Comment by thenewwazoo** [comment]
Hi @robbrechter, unfortunately, the [troubleshooting section in the README](https://github.com/thenewwazoo/homebridge-lutron-caseta-leap#%EF%B8%8F-support-and-troubleshooting) is about all the advice I've got. If you do figure out what the specific issue was, can you please report back? I'd love to collect specific recommendations based on people's successes.

**Comment by ndejong5** [comment]
I too am experiencing this issue. The gear just spins...

**Comment by TheBritishBloke** [comment]
Has there been any progress on solving this issue? I am receiving exactly the same issue and logs.

Running in Homebridge on a Synology NAS. Google Fiber Multi-Gig router. All devices running on the same network, no DMZ's or VLAN's etc.

Now that pylutron-caseta has also changed it's structure, the existing guide doesn't work and there doesn't seem to be a straightforward solution.

**Comment by thenewwazoo** [comment]
The spinner is a UX failure but indicates a real problem - the bridge can't see multicast traffic from the Caseta hub. I recently ran across something I only vaguely remember about enabling (or disabling?) IGMP (v3? snooping?) fixing mDNS discovery problems (which this is). I have also personally tried and failed to get mDNS working from inside a Docker container, so I'd be keen to make sure the Docker setup in your Synology NAS isn't a factor.

Do you have any other Homebridge plugins up and working?

**Comment by TheBritishBloke** [comment]
The only other plugin I'm running is [homebridge-tplink-smarthome v7.0.1 ](https://github.com/plasticrake/homebridge-tplink-smarthome) which has been working well.

I left the config UI open for 15 minutes and it eventually discovered the bridge, which I then paired successfully and it updated the config as follows:
`{
            "name": "Lutron",
            "platform": "LutronCasetaLeap",
            "options": {
                "filterPico": false,
                "filterBlinds": false,
                "clickSpeedDouble": "default",
                "clickSpeedLong": "default"
            },
            "secrets": [
                {
                    "bridgeid": "**REDACTED**",
                    "ca": "**REDCATED**",
                    "cert": "**REDCATED**",
                    "key": "**REDCATED**"
                }
            ]
}`

Now I just have no devices showing up in accessories. I have a PJ2-3BRL set up in the Lutron app, I also attempted removing it and setting it up again, including Homebridge restarts between each step, to no avail. The Lutron app has no problem communicating with the devices.

I should add my Homebridge is running on Ciao, as I had problems with Bonjour.

Homebridge is installed on my Synology through Package Center (as a custom source). My understanding is that this setup vs a docker container gives it native exposure as an application on the NAS, rather than being isolated (i.e. same bridge etc).

**Comment by TheBritishBloke** [comment]
Isolating the plugin to a child bridge and then restarting seemed to solve the problem. After that, the UI Settings page would find the bridge swiftly, and the Pico's showed up in Accessories instantly.

**Comment by thenewwazoo** [comment]
What?!? I really wish I had a better understanding of why (and when) child bridges make a difference. I’ll take a note to update the readme to make the suggestion a bit stronger. Thank you for following up!

**Comment by marmoten** [comment]
Hello- I am having this same issue... although in my logs, it sticks on this line, and doesn't succeed, even when I wait for several hours.

`[11/23/2023, 11:01:01 AM] [Homebridge UI] [homebridge-lutron-caseta-leap] Incoming Request: /search`

Since it doesn't ever get up and running, I am unable to set up a child bridge for it, and I tried adding the config manually with the certs and keys pulled from the caseta hub, still no luck.

Any suggestions?

**Comment by nikowebber** [comment]
@marmoten,
Were you ever able to find a solution to this? I have been using the plug-in for months now without any problem and this has just came up.
