### ISSUE TITLE
Settings screen hangs

### ISSUE THREAD

**Issue by SwimCraft101** [thenewwazoo/homebridge-lutron-caseta-leap#91]
**Description:**
The configuration menu continues to animate the loading animation indefinitely, and therefore cannot be configured.
**Reproduce:**
Simply install the plugin,  then open the settings menu
**Expected:**
It would have been expected for the plugin simply to open the settings menu and display bridges to connect
**Files:**
The plugin cannot be configured, thus no relevant information can be given here
**Environment:**
macOS with all operating programs on the latest available version

**Comment by jetlife962** [comment]
I’m having the same issue. The only difference than the above bug submission by SwimCraft101 is that I’m running my homebridge instance off of a raspberry pi 4.

**Comment by thenewwazoo** [comment]
This happens when your Homebridge host can't find a Lutron bridge via mDNS. It should probably time out eventually, though. Note that you cannot configure a bridge that can't be found automatically. Even settings up the config file won't get you there, because bridges are still discovered automatically (and then the configuration is looked up).

**Comment by jetlife962** [comment]
> This happens when your Homebridge host can't find a Lutron bridge via mDNS. It should probably time out eventually, though. Note that you cannot configure a bridge that can't be found automatically. Even settings up the config file won't get you there, because bridges are still discovered automatically (and then the configuration is looked up).

I had a sneaking suspicion that this was the case. Thank you for the help!
